package com.example.weatherapi.helpers

const val BASE_URL = "869874bb08524307bf6104813230203"
const val CURRENT = "current"
const val LOCATION = "location"
const val CONDITION = "condition"
const val FORECAST = "forecast"
const val FORECASTDAY = "forecastday"
const val NAME = "name"
const val LAST_UPDATED = "last_updated"
const val TEXT = "text"
const val TEMP_C = "temp_c"
const val ICON = "icon"
const val DATE = "date"
const val DAY = "day"
const val MAXTEMP_C = "maxtemp_c"
const val MINTEMP_C = "mintemp_c"
const val HOUR = "hour"
const val TIME = "time"